# Generated by Django 4.2.7 on 2023-11-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_myuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default='default_image.jpg'),
        ),
    ]
