# Generated by Django 4.2.7 on 2023-11-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='アイテム名'),
        ),
    ]
