# Generated by Django 4.2.7 on 2023-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_remove_upload_image_url_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('ペットボトル', 'ペットボトル'), ('紙類', '紙類'), ('缶・ビン', '缶・ビン')], default='ペットボトル', max_length=50),
        ),
    ]
