# Generated by Django 4.2.7 on 2023-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_inquiry_alter_upload_image_alter_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coupon_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_coupon',
            field=models.BooleanField(default=False),
        ),
    ]
