# Generated by Django 4.2.7 on 2023-11-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_myuser_is_staff'),
        ('backend_app', '0014_item_coupon_validity_item_is_coupon'),
    ]

    operations = [
    ]
