# Generated by Django 4.2.7 on 2023-11-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_merge_20231123_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
