# Generated by Django 4.2.7 on 2023-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_item_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='judged',
            field=models.BooleanField(default=False),
        ),
    ]
