# Generated by Django 4.2.7 on 2023-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_upload_judged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msk_url', models.URLField(default='default_image.jpg')),
            ],
        ),
    ]
