# Generated by Django 4.2.7 on 2023-11-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10代以上', '10代以上'), ('20代', '20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代以上', '60代以上')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='region',
            field=models.CharField(blank=True, choices=[('和歌山市', '和歌山市'), ('海南市', '海南市'), ('橋本市', '橋本市'), ('有田市', '有田市'), ('御坊市', '御坊市'), ('田辺市', '田辺市'), ('新宮市', '新宮市'), ('紀の川市', '紀の川市'), ('岩出市', '岩出市')], max_length=50, null=True),
        ),
    ]
