# Generated by Django 4.2.7 on 2023-11-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_myuser_age_group_myuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age_group',
            field=models.CharField(blank=True, choices=[('10代', '10代'), ('20代', '20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代以上', '60代以上')], max_length=20, null=True),
        ),
    ]
