# Generated by Django 4.2.7 on 2023-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_alter_myuser_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('和歌山市', '和歌山市'), ('海南市', '海南市'), ('橋本市', '橋本市'), ('有田市', '有田市'), ('御坊市', '御坊市'), ('田辺市', '田辺市'), ('新宮市', '新宮市'), ('紀の川市', '紀の川市'), ('岩出市', '岩出市')], max_length=50)),
                ('total_uploads', models.IntegerField(default=0)),
                ('successful_sorts', models.IntegerField(default=0)),
            ],
        ),
    ]
