# Generated by Django 4.2.7 on 2023-11-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_regionstatistics_user_age_group_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(default='default_image.jpg', unique=True, upload_to='uploads/'),
        ),
    ]
