# Generated by Django 4.2.7 on 2023-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_alter_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='uploads/'),
        ),
    ]
