# Generated by Django 4.2.7 on 2023-12-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_upload_image_hash_alter_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
